[application]
asset_dir = "assets"
out_dir = "dist"
default_platform = "web"

[web.app]
# HTML title shown before the WebAssembly application initializes.
title = "FerrisUp — Rust Project Foundations"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true

[web.resource]
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
