[application]
asset_dir = "assets"     # Directory for static assets; copied during build/serve
out_dir = "dist"        # <-- New: sets build output directory
default_platform = "web"

[web.app]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true

# HTML title tag content
title = "FerrisUp - Rust Project Bootstrapping Tool"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


