[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-run --chip RP2040"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# Enable this for better stack traces
# [profile.dev]
# debug = 1
# opt-level = "z"

# [profile.release]
# debug = 1
# opt-level = "z"
