[build]
target = "xtensa-esp32-none-elf"

[target.xtensa-esp32-none-elf]
linker = "ldproxy"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core"]
