[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-run --chip STM32F411CEUx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# For better stack traces
# [profile.dev]
# debug = 1
# opt-level = "z"

# [profile.release]
# debug = 1
# opt-level = "z"
