name: Deploy Client to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install Dioxus CLI
        run: cargo install dioxus-cli --locked
      
      - name: Build website
        run: |
          cd client
          dx build --release
      
      - name: Fix paths for GitHub Pages
        run: |
          cd target/dx/client/release/web/public
          # Create .nojekyll file to prevent GitHub Pages from processing the site with Jekyll
          touch .nojekyll
          # Copy CNAME file if it exists
          if [ -f "$GITHUB_WORKSPACE/client/public/CNAME" ]; then
            cp "$GITHUB_WORKSPACE/client/public/CNAME" .
          fi
          
          # Create assets directory if it doesn't exist
          mkdir -p assets
          
          # Copy all asset files to the assets directory
          cp -r "$GITHUB_WORKSPACE/client/assets/"* assets/
          
          # Debug - list files to verify assets are present
          echo "Listing files in build directory:"
          find . -type f | sort
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/dx/client/release/web/public'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
